module.exports = [
    {name: '投标', code: 'INVEST'},
    {name: '投标', code: 'COUPON_VOUCHER_INVEST'},
    {name: '取现', code: 'WITHDRAW'},
    {name: '充值', code: 'DEPOSIT'},
    {name: '放款', code: 'LOAN'},
    {name: '借款还款', code: 'LOAN_REPAY'},
    {name: '投资还款', code: 'INVEST_REPAY'},
    {name: '债权转让', code: 'CREDIT_ASSIGN'},
    {name: '转账扣款', code: 'TRANSFER'},
    {name: '注册奖励', code: 'REWARD_REGISTER'},
    {name: '投标奖励', code: 'REWARD_INVEST'},
    {name: '充值奖励', code: 'REWARD_DEPOSIT'},
    {name: '提现手续费', code: 'FEE_WITHDRAW'},
    {name: '身份验证手续费', code: 'FEE_AUTHENTICATE'},
    {name: '回款利息管理费', code: 'FEE_INVEST_INTEREST'},
    {name: '借款服务费', code: 'FEE_LOAN_SERVICE'},
    {name: '还款利息管理费', code: 'FEE_LOAN_INTEREST'},
    {name: '实地考察费', code: 'FEE_LOAN_VISIT'},
    {name: '担保费', code: 'FEE_LOAN_GUARANTEE'},
    {name: '逾期罚息', code: 'FEE_LOAN_PENALTY'},
    {name: '充值手续费', code: 'FEE_DEPOSIT'},
    {name: '众筹投资', code: 'CROWDFUNDING_INVEST'},
    {name: '加息券补贴', code: 'DISCOUNT_LOAN'}
];